apiVersion: v1
kind: Service
metadata:
    name: svc-${temp_name}
    labels:
        app: ${temp_name}
spec:
    type: ClusterIP
    selector:
        app: ${temp_name}
    ports:
    -   port: ${temp_port}
        protocol: TCP
        targetPort: ${temp_port}